---
- name: Copy apparmor default profile
  copy:
    src: files/Suse-apparmor-profile
    dest: /etc/apparmor.d/cri-containerd.apparmor.d
    mode: '0644'
  notify: restart apparmor
  ## Can't start apparmor service in molecule sles15 docker image
  tags: notest
