---
- name: Converge
  hosts: all
  roles:
    - role: containerd
  vars:
    _proxy: "{{ lookup('env', 'HTTP_PROXY') | urlsplit }}"
  environment:
    https_proxy: &_proxy "{{ 'http://%s:%s' |
                              format(_proxy.hostname, _proxy.port)
                              if _proxy.hostname and _proxy.port else '' }}"
    http_proxy: *_proxy
    all_proxy: *_proxy
    no_proxy: "{{ lookup('env', 'NO_PROXY') }}"
