---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint --force-color
  flake8
platforms:
  - &platform-basic
    name: molecule-docker-sles-${CI_JOB_ID:-1}
    image: ${CI_REGISTRY}/rshbintech/integrations/ckpr/infra/images/sles12sp5-systemd:${IMAGE_TAG__SLES_REGISTERED}
    registry:
      url: ${CI_REGISTRY}
      credentials:
        username: ${CI_REGISTRY_USER}
        password: ${CI_REGISTRY_PASSWORD}
    pre_build_image: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    command: /usr/lib/systemd/systemd
    stop_signal: "SIGRTMIN+3"
    tmpfs:
      - /run
    privileged: false
    capabilities:
      - SYS_ADMIN  # For systemd
      - NET_ADMIN  # For systemd
    env:
      https_proxy: "${HTTPS_PROXY}"
      http_proxy: "${HTTP_PROXY}"
      no_proxy: "${NO_PROXY}"
    # buildargs:
    #   https_proxy: ${HTTPS_PROXY}
    #   http_proxy: ${HTTP_PROXY}
    #   no_proxy: ${NO_PROXY}
provisioner:
  name: ansible
  log: true
  config_options:
    defaults:
      stdout_callback: debug
      error_on_undefined_vars: true
      callback_whitelist: profile_tasks
    diff:
      always: true
  inventory:
    host_vars:
      molecule-docker-sles-${CI_JOB_ID:-1}:
        ansible_python_interpreter: /usr/bin/python3.6
verifier:
  name: testinfra
  options:
    verbose: true
